# Generated by Django 5.2.6 on 2025-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Displayed Price')),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Surface Area (m²)')),
                ('property_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property Tax')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('rental_start_date', models.DateField(verbose_name='Rental Start Date')),
                ('deferral_period', models.IntegerField(default=0, verbose_name='Deferral Period (months)')),
                ('first_year_rental_months', models.IntegerField(verbose_name='Rental Months in 1st Year')),
                ('price_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per m²')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Rent')),
                ('rent_per_square_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rent per m²')),
            ],
            options={
                'verbose_name': 'Real Estate Property',
                'verbose_name_plural': 'Real Estate Properties',
            },
        ),
    ]
