# Generated by Django 5.2.6 on 2025-09-25 21:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format.')])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_document', models.FileField(blank=True, help_text='Scan of ID or passport.', upload_to='tenants/id_documents/')),
                ('emergency_contact', models.CharField(blank=True, help_text='Name and phone of emergency contact.', max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('total_general_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total General Charges')),
                ('has_individual_meters', models.BooleanField(default=True, help_text='Can individual consumption (water, electricity) be measured per unit?', verbose_name='Individual Meters')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='rentals.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room (for shared accommodation)')], max_length=20, verbose_name='Unit Type')),
                ('unit_number', models.CharField(help_text='Apartment number, room number, or other identifier.', max_length=50, verbose_name='Unit Number')),
                ('size_m2', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Size (m²)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Rent')),
                ('specific_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Specific Charges')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_units', to='rentals.building', verbose_name='Building')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_units', to='rentals.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Real Estate Unit',
                'verbose_name_plural': 'Real Estate Units',
                'ordering': ['building__name', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_type', models.CharField(choices=[('standard', 'Standard Lease'), ('colocation', 'Colocation (Shared Accommodation)')], default='standard', max_length=20, verbose_name='Lease Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('has_solidarity_clause', models.BooleanField(default=False, help_text='For colocations: if True, all tenants are jointly liable.', verbose_name='Solidarity Clause')),
                ('flat_rate_charges', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly charges (used when individual consumption cannot be measured).', max_digits=10, verbose_name='Flat Rate Charges')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount.', max_digits=10, verbose_name='Deposit Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('contract_document', models.FileField(blank=True, help_text='Signed contract document (PDF).', upload_to='lease_contracts/', verbose_name='Contract Document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('real_estate_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='rentals.realestateunit', verbose_name='Real Estate Unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='rentals.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Lease Contract',
                'verbose_name_plural': 'Lease Contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChargeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of general charges allocated to this property (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_distributions', to='rentals.building')),
                ('real_estate_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_distributions', to='rentals.realestateunit')),
            ],
            options={
                'verbose_name': 'Charge Distribution',
                'verbose_name_plural': 'Charge Distributions',
                'unique_together': {('building', 'real_estate_unit', 'start_date')},
            },
        ),
    ]
