# Generated by Django 5.2.6 on 2025-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateunit',
            name='unit_number',
            field=models.CharField(help_text='Apartment number, room number, or another identifier.', max_length=50, verbose_name='Unit Number'),
        ),
    ]
